public class ApexLimitConstants {
    
   	public Static final Integer maxParameter=10;
	public Static final Integer maxTextLength=255;
    public Static final Integer maxNumberLength=18;
    public Static final Integer minLength=0;
    public Static final Integer maxLongTextAreaLength=131072;
    public Static final Integer maxRichTextAreaLength=32768;
    public Static final Integer maxVisibleLinesLongTextArea=50;
    public Static final Integer minVisibleLinesLongTextArea=2;
    public Static final Integer maxVisibleLinesMultiSelectPicklist=10;
    public Static final Integer minVisibleLinesMultiSelectPicklist=3;
    public Static final Integer minVisibleLinesRichTextArea=10;
    public Static final Integer maxVisibleLinesRichTextArea=50;
}