Objec Name,Type,Field Label,Field Name,Length,Decimal Places,Visible Lines,Picklist Values,Picklist Sorted,Default Value,Required,Track Field History,Unique,External Id,Description,Help Text
Test__c,Text,Testing 104,Testing  104,255,0,,,,,TRUE,TRUE,TRUE,TRUE,Text Field Description,Text Field Help Text
Test__c,Text,Testing 105,Testing 105,,0,,,,,TRUE,TRUE,TRUE,TRUE,Text Field Description,Text Field Help Text
Test__c,Text,Testing 106,Testing 106,255,0,,,,,TRUE,TRUE,TRUE,TRUE,Text Field Description,Text Field Help Text
